# Generated by Django 3.2.9 on 2021-11-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211126_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultimages/default.jpeg', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(blank=True, default='defaultimages/defaultcover.png', null=True, upload_to='headers'),
        ),
    ]
