# Generated by Django 3.2.9 on 2021-11-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='category',
            new_name='tag',
        ),
    ]
