# Generated by Django 3.2.9 on 2021-11-24 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 11, 24, 18, 43, 40, 28617, tzinfo=utc), max_length=455),
            preserve_default=False,
        ),
    ]
